/*
 * Cloud Resource & Information Management System (CRIMSy)
 * Copyright 2023 Leibniz-Institut f. Pflanzenbiochemie
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package de.ipb_halle.test;

import jakarta.enterprise.concurrent.ContextService;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;
import java.util.concurrent.RejectedExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import jakarta.enterprise.concurrent.ManagedExecutorService;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.function.Supplier;

/**
 * Mock implementation of ManagedExecutorService that can hold maxTasks submitted
 * tasks.
 * 
 * @author flange
 */
public class ManagedExecutorServiceMock implements ManagedExecutorService {

    private int maxTasks;
    private List<Runnable> submittedTasks = new ArrayList<>();

    public ManagedExecutorServiceMock(int maxTasks) {
        this.maxTasks = maxTasks;
    }

    @Override
    public Future<?> submit(Runnable task) {
        if (submittedTasks.size() < maxTasks) {
            submittedTasks.add(task);
        } else {
            throw new RejectedExecutionException();
        }
        return null;
    }

    public void reset() {
        submittedTasks.clear();
    }

    public List<Runnable> getSubmittedTasks() {
        return submittedTasks;
    }

    @Override
    public void shutdown() {
    }

    @Override
    public List<Runnable> shutdownNow() {
        return null;
    }

    @Override
    public boolean isShutdown() {
        return false;
    }

    @Override
    public boolean isTerminated() {
        return false;
    }

    @Override
    public boolean awaitTermination(long timeout, TimeUnit unit) throws InterruptedException {
        return false;
    }

    @Override
    public <T> Future<T> submit(Callable<T> task) {
        return null;
    }

    @Override
    public <T> Future<T> submit(Runnable task, T result) {
        return null;
    }

    @Override
    public <T> List<Future<T>> invokeAll(Collection<? extends Callable<T>> tasks) throws InterruptedException {
        return null;
    }

    @Override
    public <T> List<Future<T>> invokeAll(Collection<? extends Callable<T>> tasks, long timeout, TimeUnit unit)
            throws InterruptedException {
        return null;
    }

    @Override
    public <T> T invokeAny(Collection<? extends Callable<T>> tasks) throws InterruptedException, ExecutionException {
        return null;
    }

    @Override
    public <T> T invokeAny(Collection<? extends Callable<T>> tasks, long timeout, TimeUnit unit)
            throws InterruptedException, ExecutionException, TimeoutException {
        return null;
    }

    @Override
    public void execute(Runnable command) {
    }

    /*
     * autogenerated asynchronouse methods
     */
    @Override
    public <U> CompletableFuture<U> completedFuture(U u) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    @Override
    public <U> CompletionStage<U> completedStage(U u) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    @Override
    public <T> CompletableFuture<T> copy(CompletableFuture<T> cf) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    @Override
    public <T> CompletionStage<T> copy(CompletionStage<T> cs) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    @Override
    public <U> CompletableFuture<U> failedFuture(Throwable thrwbl) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    @Override
    public <U> CompletionStage<U> failedStage(Throwable thrwbl) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    @Override
    public ContextService getContextService() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    @Override
    public <U> CompletableFuture<U> newIncompleteFuture() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    @Override
    public CompletableFuture<Void> runAsync(Runnable r) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    @Override
    public <U> CompletableFuture<U> supplyAsync(Supplier<U> splr) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
}
