include(target/cypress/config_m4.inc)dnl
{ 
    "testURL": "https://TESTBASE_HOSTNAME/ui/index.xhtml",
    "groupName": "TESTgroup2",
    "userLogin": "user2",
    "userName":  "TESTuser2",
    "compounds": [ 
        {
            "name" : "Phenol",
            "casrn" : "108-95-2",
            "mol" : "n.n.\n\ngenerated by MolPaintJS\n  0  0  0  0  0  0            999 V3000\nM  V30 BEGIN CTAB\nM  V30 COUNTS 7 7 0 0 0\nM  V30 BEGIN ATOM\nM  V30 1 C -1.1645 0.4842 0.0000 0\nM  V30 2 C -1.1645 -0.3408 0.0000 0\nM  V30 3 C -0.4500 -0.7533 0.0000 0\nM  V30 4 C 0.2645 -0.3408 0.0000 0\nM  V30 5 C 0.2645 0.4842 0.0000 0\nM  V30 6 C -0.4500 0.8967 0.0000 0\nM  V30 7 O -0.4500 1.7217 0.0000 0\nM  V30 END ATOM\nM  V30 BEGIN BOND\nM  V30 1 2 1 2\nM  V30 2 1 2 3\nM  V30 3 2 3 4\nM  V30 4 1 4 5\nM  V30 5 2 5 6\nM  V30 6 1 6 1\nM  V30 7 1 6 7\nM  V30 END BOND\nM  V30 END CTAB\nM  END\n" 
        }, {
            "name" : "Benzene",
            "casrn" : "71-43-2",
            "mol" : "n.n.\n\ngenerated by MolPaintJS\n  0  0  0  0  0  0            999 V3000\nM  V30 BEGIN CTAB\nM  V30 COUNTS 6 6 0 0 0\nM  V30 BEGIN ATOM\nM  V30 1 C -0.6895 1.4342 0.0000 0\nM  V30 2 C -0.6895 0.6092 0.0000 0\nM  V30 3 C 0.0250 0.1967 0.0000 0\nM  V30 4 C 0.7395 0.6092 0.0000 0\nM  V30 5 C 0.7395 1.4342 0.0000 0\nM  V30 6 C 0.0250 1.8467 0.0000 0\nM  V30 END ATOM\nM  V30 BEGIN BOND\nM  V30 1 2 1 2\nM  V30 2 1 2 3\nM  V30 3 2 3 4\nM  V30 4 1 4 5\nM  V30 5 2 5 6\nM  V30 6 1 6 1\nM  V30 END BOND\nM  V30 END CTAB\nM  END\n"
        }, {
            "name" : "Ethoxybenzene",
            "casrn" : "103-73-1",
            "mol": "n.n.\n\ngenerated by MolPaintJS\n  0  0  0  0  0  0            999 V3000\nM  V30 BEGIN CTAB\nM  V30 COUNTS 9 9 0 0 0\nM  V30 BEGIN ATOM\nM  V30 1 C -0.6895 1.4342 0.0000 0\nM  V30 2 C -0.6895 0.6092 0.0000 0\nM  V30 3 C 0.0250 0.1967 0.0000 0\nM  V30 4 C 0.7395 0.6092 0.0000 0\nM  V30 5 C 0.7395 1.4342 0.0000 0\nM  V30 6 C 0.0250 1.8467 0.0000 0\nM  V30 7 O 0.0250 2.6717 0.0000 0\nM  V30 8 C 0.7395 3.0842 0.0000 0\nM  V30 9 C 0.7395 3.9092 0.0000 0\nM  V30 END ATOM\nM  V30 BEGIN BOND\nM  V30 1 2 1 2\nM  V30 2 1 2 3\nM  V30 3 2 3 4\nM  V30 4 1 4 5\nM  V30 5 2 5 6\nM  V30 6 1 6 1\nM  V30 7 1 6 7\nM  V30 8 1 7 8\nM  V30 9 1 8 9\nM  V30 END BOND\nM  V30 END CTAB\nM  END\n"
        } ]
}

