#
# HTTP Installation Web Server for integration testing
# (c) 2020 Leibniz Institut f. Pflanzenbiochemie 
#
# how to build from current dir:
#	docker build -f Dockerfile -t crimsyci .
#
# run command: 
#	docker run \
#	  -p 8000:80 \
#         --mount type=bind,src=/data,dst=/usr/local/apache2/htdocs
#	  crimsyci
#
#
FROM httpd 

