/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * API specification for managing research materials, users, authentication, search capabilities, administration workflows, and audit logging. Designed for integration with React frontends and Java/Jakarta backend services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuditLog
 */
export interface AuditLog {
    /**
     * 
     * @type {number}
     * @memberof AuditLog
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AuditLog
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof AuditLog
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditLog
     */
    entity?: string;
    /**
     * 
     * @type {Date}
     * @memberof AuditLog
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the AuditLog interface.
 */
export function instanceOfAuditLog(value: object): value is AuditLog {
    return true;
}

export function AuditLogFromJSON(json: any): AuditLog {
    return AuditLogFromJSONTyped(json, false);
}

export function AuditLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditLog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'action': json['action'] == null ? undefined : json['action'],
        'entity': json['entity'] == null ? undefined : json['entity'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function AuditLogToJSON(json: any): AuditLog {
    return AuditLogToJSONTyped(json, false);
}

export function AuditLogToJSONTyped(value?: AuditLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'action': value['action'],
        'entity': value['entity'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
    };
}

