/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * API specification for managing research materials, users, authentication, search capabilities, administration workflows, and audit logging. Designed for integration with React frontends and Java/Jakarta backend services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthToken
 */
export interface AuthToken {
    /**
     * Token
     * @type {string}
     * @memberof AuthToken
     */
    token: string;
    /**
     * Session validity duration in seconds
     * @type {number}
     * @memberof AuthToken
     */
    expiresInSeconds: number;
}

/**
 * Check if a given object implements the AuthToken interface.
 */
export function instanceOfAuthToken(value: object): value is AuthToken {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('expiresInSeconds' in value) || value['expiresInSeconds'] === undefined) return false;
    return true;
}

export function AuthTokenFromJSON(json: any): AuthToken {
    return AuthTokenFromJSONTyped(json, false);
}

export function AuthTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthToken {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'expiresInSeconds': json['expiresInSeconds'],
    };
}

export function AuthTokenToJSON(json: any): AuthToken {
    return AuthTokenToJSONTyped(json, false);
}

export function AuthTokenToJSONTyped(value?: AuthToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'expiresInSeconds': value['expiresInSeconds'],
    };
}

