/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    username?: string;
    /**
     * Bearer token for authentication
     * @type {string}
     * @memberof AuthResponse
     */
    token?: string;
    /**
     * Session validity duration in seconds
     * @type {number}
     * @memberof AuthResponse
     */
    expiresInSeconds?: number;
}

/**
 * Check if a given object implements the AuthResponse interface.
 */
export function instanceOfAuthResponse(value: object): value is AuthResponse {
    return true;
}

export function AuthResponseFromJSON(json: any): AuthResponse {
    return AuthResponseFromJSONTyped(json, false);
}

export function AuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'username': json['username'] == null ? undefined : json['username'],
        'token': json['token'] == null ? undefined : json['token'],
        'expiresInSeconds': json['expiresInSeconds'] == null ? undefined : json['expiresInSeconds'],
    };
}

export function AuthResponseToJSON(json: any): AuthResponse {
    return AuthResponseToJSONTyped(json, false);
}

export function AuthResponseToJSONTyped(value?: AuthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'username': value['username'],
        'token': value['token'],
        'expiresInSeconds': value['expiresInSeconds'],
    };
}

