/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * API specification for managing research materials, users, authentication, search capabilities, administration workflows, and audit logging. Designed for integration with React frontends and Java/Jakarta backend services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUser
 */
export interface AuthUser {
    /**
     * Unique user ID
     * @type {number}
     * @memberof AuthUser
     */
    id: number;
    /**
     * User login name
     * @type {string}
     * @memberof AuthUser
     */
    username: string;
    /**
     * Full name
     * @type {string}
     * @memberof AuthUser
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUser
     */
    email?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthUser
     */
    groups?: Array<string>;
    /**
     * Indicates whether the user belongs to the Admin Group
     * @type {boolean}
     * @memberof AuthUser
     */
    admin?: boolean;
}

/**
 * Check if a given object implements the AuthUser interface.
 */
export function instanceOfAuthUser(value: object): value is AuthUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function AuthUserFromJSON(json: any): AuthUser {
    return AuthUserFromJSONTyped(json, false);
}

export function AuthUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'groups': json['groups'] == null ? undefined : json['groups'],
        'admin': json['admin'] == null ? undefined : json['admin'],
    };
}

export function AuthUserToJSON(json: any): AuthUser {
    return AuthUserToJSONTyped(json, false);
}

export function AuthUserToJSONTyped(value?: AuthUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'name': value['name'],
        'email': value['email'],
        'groups': value['groups'],
        'admin': value['admin'],
    };
}

