/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * API specification for managing research materials, users, authentication, search capabilities, administration workflows, and audit logging. Designed for integration with React frontends and Java/Jakarta backend services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteUser200Response
 */
export interface DeleteUser200Response {
    /**
     * 
     * @type {string}
     * @memberof DeleteUser200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the DeleteUser200Response interface.
 */
export function instanceOfDeleteUser200Response(value: object): value is DeleteUser200Response {
    return true;
}

export function DeleteUser200ResponseFromJSON(json: any): DeleteUser200Response {
    return DeleteUser200ResponseFromJSONTyped(json, false);
}

export function DeleteUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUser200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function DeleteUser200ResponseToJSON(json: any): DeleteUser200Response {
    return DeleteUser200ResponseToJSONTyped(json, false);
}

export function DeleteUser200ResponseToJSONTyped(value?: DeleteUser200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

