/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MaterialType = {
    Structure: 'Structure',
    Sequence: 'Sequence',
    Biomaterial: 'Biomaterial',
    Composition: 'Composition',
    None: 'NONE'
} as const;
export type MaterialType = typeof MaterialType[keyof typeof MaterialType];


export function instanceOfMaterialType(value: any): boolean {
    for (const key in MaterialType) {
        if (Object.prototype.hasOwnProperty.call(MaterialType, key)) {
            if (MaterialType[key as keyof typeof MaterialType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MaterialTypeFromJSON(json: any): MaterialType {
    return MaterialTypeFromJSONTyped(json, false);
}

export function MaterialTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaterialType {
    return json as MaterialType;
}

export function MaterialTypeToJSON(value?: MaterialType | null): any {
    return value as any;
}

export function MaterialTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): MaterialType {
    return value as MaterialType;
}

