/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface PagedUsers
 */
export interface PagedUsers {
    /**
     * 
     * @type {number}
     * @memberof PagedUsers
     */
    totalUsers: number;
    /**
     * 
     * @type {number}
     * @memberof PagedUsers
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PagedUsers
     */
    currentPage: number;
    /**
     * 
     * @type {Array<User>}
     * @memberof PagedUsers
     */
    users: Array<User>;
}

/**
 * Check if a given object implements the PagedUsers interface.
 */
export function instanceOfPagedUsers(value: object): value is PagedUsers {
    if (!('totalUsers' in value) || value['totalUsers'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function PagedUsersFromJSON(json: any): PagedUsers {
    return PagedUsersFromJSONTyped(json, false);
}

export function PagedUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedUsers {
    if (json == null) {
        return json;
    }
    return {
        
        'totalUsers': json['totalUsers'],
        'totalPages': json['totalPages'],
        'currentPage': json['currentPage'],
        'users': ((json['users'] as Array<any>).map(UserFromJSON)),
    };
}

export function PagedUsersToJSON(json: any): PagedUsers {
    return PagedUsersToJSONTyped(json, false);
}

export function PagedUsersToJSONTyped(value?: PagedUsers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalUsers': value['totalUsers'],
        'totalPages': value['totalPages'],
        'currentPage': value['currentPage'],
        'users': ((value['users'] as Array<any>).map(UserToJSON)),
    };
}

