/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * API specification for managing research materials, users, authentication, search capabilities, administration workflows, and audit logging. Designed for integration with React frontends and Java/Jakarta backend services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSummary } from './UserSummary';
import {
    UserSummaryFromJSON,
    UserSummaryFromJSONTyped,
    UserSummaryToJSON,
    UserSummaryToJSONTyped,
} from './UserSummary';

/**
 * 
 * @export
 * @interface PaginatedUserResponse
 */
export interface PaginatedUserResponse {
    /**
     * 
     * @type {Array<UserSummary>}
     * @memberof PaginatedUserResponse
     */
    items: Array<UserSummary>;
    /**
     * Total number of users in the system
     * @type {number}
     * @memberof PaginatedUserResponse
     */
    totalItems: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginatedUserResponse
     */
    totalPages: number;
    /**
     * Current page number
     * @type {number}
     * @memberof PaginatedUserResponse
     */
    currentPage: number;
}

/**
 * Check if a given object implements the PaginatedUserResponse interface.
 */
export function instanceOfPaginatedUserResponse(value: object): value is PaginatedUserResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    return true;
}

export function PaginatedUserResponseFromJSON(json: any): PaginatedUserResponse {
    return PaginatedUserResponseFromJSONTyped(json, false);
}

export function PaginatedUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UserSummaryFromJSON)),
        'totalItems': json['totalItems'],
        'totalPages': json['totalPages'],
        'currentPage': json['currentPage'],
    };
}

export function PaginatedUserResponseToJSON(json: any): PaginatedUserResponse {
    return PaginatedUserResponseToJSONTyped(json, false);
}

export function PaginatedUserResponseToJSONTyped(value?: PaginatedUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(UserSummaryToJSON)),
        'totalItems': value['totalItems'],
        'totalPages': value['totalPages'],
        'currentPage': value['currentPage'],
    };
}

