/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaterialType } from './MaterialType';
import {
    MaterialTypeFromJSON,
    MaterialTypeFromJSONTyped,
    MaterialTypeToJSON,
    MaterialTypeToJSONTyped,
} from './MaterialType';
import type { SearchType } from './SearchType';
import {
    SearchTypeFromJSON,
    SearchTypeFromJSONTyped,
    SearchTypeToJSON,
    SearchTypeToJSONTyped,
} from './SearchType';

/**
 * 
 * @export
 * @interface SearchResult
 */
export interface SearchResult {
    /**
     * 
     * @type {SearchType}
     * @memberof SearchResult
     */
    domain?: SearchType;
    /**
     * 
     * @type {MaterialType}
     * @memberof SearchResult
     */
    subtype?: MaterialType;
    /**
     * 
     * @type {number}
     * @memberof SearchResult
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    label?: string;
}



/**
 * Check if a given object implements the SearchResult interface.
 */
export function instanceOfSearchResult(value: object): value is SearchResult {
    return true;
}

export function SearchResultFromJSON(json: any): SearchResult {
    return SearchResultFromJSONTyped(json, false);
}

export function SearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'] == null ? undefined : SearchTypeFromJSON(json['domain']),
        'subtype': json['subtype'] == null ? undefined : MaterialTypeFromJSON(json['subtype']),
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function SearchResultToJSON(json: any): SearchResult {
    return SearchResultToJSONTyped(json, false);
}

export function SearchResultToJSONTyped(value?: SearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': SearchTypeToJSON(value['domain']),
        'subtype': MaterialTypeToJSON(value['subtype']),
        'id': value['id'],
        'label': value['label'],
    };
}

