/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaterialType } from './MaterialType';
import {
    MaterialTypeFromJSON,
    MaterialTypeFromJSONTyped,
    MaterialTypeToJSON,
    MaterialTypeToJSONTyped,
} from './MaterialType';
import type { SearchType } from './SearchType';
import {
    SearchTypeFromJSON,
    SearchTypeFromJSONTyped,
    SearchTypeToJSON,
    SearchTypeToJSONTyped,
} from './SearchType';

/**
 * 
 * @export
 * @interface SearchRequest
 */
export interface SearchRequest {
    /**
     * Selected top-level search domains
     * Examples: Materials, Items, Experiments, Documents
     * 
     * @type {Array<SearchType>}
     * @memberof SearchRequest
     */
    searchTypes?: Array<SearchType>;
    /**
     * Only used when Materials is selected
     * Examples: Structure, Sequence, Biomaterial, Composition
     * 
     * @type {Array<MaterialType>}
     * @memberof SearchRequest
     */
    materialTypes?: Array<MaterialType>;
    /**
     * Free-text search query
     * @type {string}
     * @memberof SearchRequest
     */
    query?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchRequest
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchRequest
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the SearchRequest interface.
 */
export function instanceOfSearchRequest(value: object): value is SearchRequest {
    return true;
}

export function SearchRequestFromJSON(json: any): SearchRequest {
    return SearchRequestFromJSONTyped(json, false);
}

export function SearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'searchTypes': json['searchTypes'] == null ? undefined : ((json['searchTypes'] as Array<any>).map(SearchTypeFromJSON)),
        'materialTypes': json['materialTypes'] == null ? undefined : ((json['materialTypes'] as Array<any>).map(MaterialTypeFromJSON)),
        'query': json['query'] == null ? undefined : json['query'],
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
    };
}

export function SearchRequestToJSON(json: any): SearchRequest {
    return SearchRequestToJSONTyped(json, false);
}

export function SearchRequestToJSONTyped(value?: SearchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'searchTypes': value['searchTypes'] == null ? undefined : ((value['searchTypes'] as Array<any>).map(SearchTypeToJSON)),
        'materialTypes': value['materialTypes'] == null ? undefined : ((value['materialTypes'] as Array<any>).map(MaterialTypeToJSON)),
        'query': value['query'],
        'page': value['page'],
        'pageSize': value['pageSize'],
    };
}

