/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * API specification for managing research materials, users, authentication, search capabilities, administration workflows, and audit logging. Designed for integration with React frontends and Java/Jakarta backend services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSummary
 */
export interface UserSummary {
    /**
     * User ID
     * @type {number}
     * @memberof UserSummary
     */
    id: number;
    /**
     * Full name
     * @type {string}
     * @memberof UserSummary
     */
    name?: string;
    /**
     * Email address
     * @type {string}
     * @memberof UserSummary
     */
    email?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserSummary
     */
    groups?: Array<string>;
    /**
     * Indicates whether the user belongs to the Admin Group
     * @type {boolean}
     * @memberof UserSummary
     */
    admin?: boolean;
}

/**
 * Check if a given object implements the UserSummary interface.
 */
export function instanceOfUserSummary(value: object): value is UserSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserSummaryFromJSON(json: any): UserSummary {
    return UserSummaryFromJSONTyped(json, false);
}

export function UserSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'groups': json['groups'] == null ? undefined : json['groups'],
        'admin': json['admin'] == null ? undefined : json['admin'],
    };
}

export function UserSummaryToJSON(json: any): UserSummary {
    return UserSummaryToJSONTyped(json, false);
}

export function UserSummaryToJSONTyped(value?: UserSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'groups': value['groups'],
        'admin': value['admin'],
    };
}

