/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * API specification for managing research materials, users, authentication, search capabilities, administration workflows, and audit logging. Designed for integration with React frontends and Java/Jakarta backend services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuditLog,
} from '../models/index';
import {
    AuditLogFromJSON,
    AuditLogToJSON,
} from '../models/index';

/**
 * 
 */
export class AuditLogsApi extends runtime.BaseAPI {

    /**
     * Returns system activity logs for compliance and debugging. Logs include user actions and administrative events. 
     * Retrieve audit logs
     */
    async auditLogsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AuditLog>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/audit/logs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AuditLogFromJSON));
    }

    /**
     * Returns system activity logs for compliance and debugging. Logs include user actions and administrative events. 
     * Retrieve audit logs
     */
    async auditLogsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AuditLog>> {
        const response = await this.auditLogsGetRaw(initOverrides);
        return await response.value();
    }

}
