/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  SearchRequest,
  SearchResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    SearchRequestFromJSON,
    SearchRequestToJSON,
    SearchResponseFromJSON,
    SearchResponseToJSON,
} from '../models/index';

export interface SearchOperationRequest {
    searchRequest: SearchRequest;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * Performs search across Materials, Items, Experiments and Documents.   If \"Materials\" is included in searchTypes, materialTypes may be provided  (Structure, Sequence, Biomaterial, Composition).        All values are currently treated as string (for being simple as possible). 
     * Unified search endpoint
     */
    async searchRaw(requestParameters: SearchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponse>> {
        if (requestParameters['searchRequest'] == null) {
            throw new runtime.RequiredError(
                'searchRequest',
                'Required parameter "searchRequest" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("SessionKeyAuthentication", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchRequestToJSON(requestParameters['searchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResponseFromJSON(jsonValue));
    }

    /**
     * Performs search across Materials, Items, Experiments and Documents.   If \"Materials\" is included in searchTypes, materialTypes may be provided  (Structure, Sequence, Biomaterial, Composition).        All values are currently treated as string (for being simple as possible). 
     * Unified search endpoint
     */
    async search(requestParameters: SearchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponse> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
