/* tslint:disable */
/* eslint-disable */
/**
 * CRIMSy API
 * API specification for managing research materials, users, authentication, search capabilities, administration workflows, and audit logging. Designed for integration with React frontends and Java/Jakarta backend services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PaginatedUserResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PaginatedUserResponseFromJSON,
    PaginatedUserResponseToJSON,
} from '../models/index';

export interface GetUsersListRequest {
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Returns all users from the system with basic details. Useful for populating user lists in the frontend. 
     * Retrieve list of all users
     */
    async getUsersListRaw(requestParameters: GetUsersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedUserResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedUserResponseFromJSON(jsonValue));
    }

    /**
     * Returns all users from the system with basic details. Useful for populating user lists in the frontend. 
     * Retrieve list of all users
     */
    async getUsersList(requestParameters: GetUsersListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedUserResponse> {
        const response = await this.getUsersListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
