# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ LBAC-60-CloudLIMS ]
  pull_request:
    branches: [ LBAC-60-CloudLIMS ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      env:
        TOMCAT_HOME: /tmp
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Code coverage report
      run: mvn -B -Dcobertura.report.format=xml -DskipTests cobertura:cobertura
    - name: Code coverage badge
      uses: codecov/codecov-action@v1
      with:
        directory: ./ui/target/site/cobertura/
        fail_ci_if_error: false
        file: cobertura.xml
        flags: unittests
